"""Observable-event session summary. Isolation Forest is diagnostic only — never adjudication."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any


VERDICT_FORBIDDEN = ("CHEAT DETECTED", "CLEAN", "SUSPICIOUS", "GUILTY", "CHEATING")


class ObservableSessionSummary:
    def __init__(self, session_dir: str | Path) -> None:
        self.session_dir = Path(session_dir)
        self.log_file = self.session_dir / "events.jsonl"
        self.report_file = self.session_dir / "FINAL_REPORT.md"

    def analyze(self) -> dict[str, Any]:
        events: list[dict[str, Any]] = []
        if self.log_file.exists():
            with self.log_file.open(encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        events.append(json.loads(line))
                    except json.JSONDecodeError:
                        continue
        counts: dict[str, int] = {}
        timeline: list[str] = []
        start = end = None
        for rec in events:
            etype = str(rec.get("type", "UNKNOWN"))
            counts[etype] = counts.get(etype, 0) + 1
            ts = rec.get("timestamp", "")
            timeline.append(f"- {ts}: {etype} {rec.get('data', '')}")
            try:
                parsed = datetime.fromisoformat(str(ts).replace("Z", "+00:00"))
            except ValueError:
                continue
            start = parsed if start is None else min(start, parsed)
            end = parsed if end is None else max(end, parsed)

        diagnostic = self._diagnostic_novelty(events)
        duration = int((end - start).total_seconds()) if start and end else 0
        report = self._render(counts, timeline, duration, diagnostic)
        self.report_file.write_text(report, encoding="utf-8")
        return {"counts": counts, "duration_seconds": duration, "diagnostic": diagnostic}

    def _diagnostic_novelty(self, events: list[dict[str, Any]]) -> str:
        try:
            from ai.ml_model import AdvancedAnomalyDetector

            metrics = []
            for rec in events:
                if rec.get("type") == "METRICS" and isinstance(rec.get("data"), dict):
                    data = dict(rec["data"])
                    if rec.get("timestamp"):
                        try:
                            data["timestamp_obj"] = datetime.fromisoformat(
                                str(rec["timestamp"]).replace("Z", "+00:00")
                            )
                        except ValueError:
                            pass
                    metrics.append(data)
            if not metrics:
                return "Isolation Forest diagnostic skipped (no METRICS rows)."
            model = AdvancedAnomalyDetector()
            anomalies = model.train_and_detect(metrics)
            return (
                "Isolation Forest novelty signal (diagnostic only, not adjudication): "
                f"{len(anomalies)} unusual windows. This is not a guilt verdict."
            )
        except Exception as exc:  # noqa: BLE001
            return f"Isolation Forest diagnostic unavailable: {exc}"

    def _render(self, counts: dict[str, int], timeline: list[str], duration: int, diagnostic: str) -> str:
        lines = [
            "# Observable Session Summary",
            "",
            "This report lists **evidence and observations only**. It does not assign guilt.",
            "",
            f"- Duration: {duration // 60} min {duration % 60} sec",
            f"- Event counts: {json.dumps(counts, sort_keys=True)}",
            "",
            "## Diagnostic novelty (not a verdict)",
            diagnostic,
            "",
            "## Timeline",
            *(timeline or ["- (no events)"]),
            "",
            "---",
            "*Generated by Phone-Proctor observable-event summary*",
        ]
        text = "\n".join(lines)
        for banned in VERDICT_FORBIDDEN:
            if banned in text:
                text = text.replace(banned, "OBSERVATION")
        return text
